apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    server {
      listen 80;

      location / {
        root /var/www/html;
        try_files $uri /index.php$is_args$args;
      }

      location ~ \.php$ {
        fastcgi_pass php-fpm-service:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        include fastcgi_params;
      }
    }