apiVersion: v1
kind: PersistentVolume
metadata:
  name: symfony-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/adrn/pg-b/pg-back
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: symfony-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi